artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  test_metric_file_path: artifacts/model_evaluation/metrics.json

model_prediction:
  root_dir: artifacts/model_prediction
  model_path: artifacts/model_trainer/model.joblib
  predictions_file_path: artifacts/model_prediction/predictions.csv


  # ==============================
# 🔹 CONFIGURATION FOR ARTIFACTS & PIPELINE COMPONENTS
# ==============================

# ✅ Define the root directory for all artifacts generated during the pipeline execution.
artifacts_root: artifacts

# ==============================
# 🔹 DATA INGESTION CONFIGURATION
# ==============================
data_ingestion:
  # ✅ Root directory where data ingestion artifacts will be stored.
  root_dir: artifacts/data_ingestion
  # ✅ URL to download the dataset.
  source_URL:   https://github.com/megokul/pilotproject/tree/main/datasets/winequality-data.zip
  # ✅ Local file path for the downloaded data zip file.
  local_data_file: artifacts/data_ingestion/data.zip
  # ✅ Directory where the zip file will be unzipped.
  unzip_dir: artifacts/data_ingestion

# ==============================
# 🔹 DATA VALIDATION CONFIGURATION
# ==============================
data_validation:
  # ✅ Root directory where data validation artifacts will be stored.
  root_dir: artifacts/data_validation
  # ✅ File path to the unzipped data for validation.
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  # ✅ File to track the status of the data validation process.
  STATUS_FILE: artifacts/data_validation/status.txt

# ==============================
# 🔹 DATA TRANSFORMATION CONFIGURATION
# ==============================
data_transformation:
  # ✅ Root directory where data transformation artifacts will be stored.
  root_dir: artifacts/data_transformation
  # ✅ Input data path for the transformation process.
  data_path: artifacts/data_ingestion/winequality-red.csv
  # ✅ Status file for tracking the data transformation process.
  STATUS_FILE: artifacts/data_validation/status.txt

# ==============================
# 🔹 MODEL TRAINING CONFIGURATION
# ==============================
model_trainer:
  # ✅ Root directory where model training artifacts will be stored.
  root_dir: artifacts/model_trainer
  # ✅ File path for training data generated during data transformation.
  train_data_path: artifacts/data_transformation/train.csv
  # ✅ File path for testing data generated during data transformation.
  test_data_path: artifacts/data_transformation/test.csv
  # ✅ Name of the file where the trained model will be saved.
  model_name: model.joblib

# ==============================
# 🔹 MODEL EVALUATION CONFIGURATION
# ==============================
model_evaluation:
  # ✅ Root directory where model evaluation artifacts will be stored.
  root_dir: artifacts/model_evaluation
  # ✅ File path for testing data used in model evaluation.
  test_data_path: artifacts/data_transformation/test.csv
  # ✅ Path to the trained model that will be evaluated.
  model_path: artifacts/model_trainer/model.joblib
  # ✅ File path to save the evaluation metrics (e.g., accuracy, F1 score).
  test_metric_file_path: artifacts/model_evaluation/metrics.json

# ==============================
# 🔹 MODEL PREDICTION CONFIGURATION
# ==============================
model_prediction:
  # ✅ Root directory where model prediction artifacts will be stored.
  root_dir: artifacts/model_prediction
  # ✅ Path to the trained model used for making predictions.
  model_path: artifacts/model_trainer/model.joblib
  # ✅ File path where the model's predictions will be saved.
  predictions_file_path: artifacts/model_prediction/predictions.csv
