# ==============================
# Project Artifacts Root
# ==============================

# Directory where all pipeline-related outputs will be saved
artifacts_root: artifacts

# ==============================
# Data Ingestion Configuration
# ==============================

data_ingestion:
  # Directory for all data ingestion outputs
  root_dir: artifacts/data_ingestion
  
  # Remote URL to download the dataset
  source_URL: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip
  
  # Path to save the downloaded zip file
  local_data_file: artifacts/data_ingestion/data.zip
  
  # Directory to extract the contents of the zip file
  unzip_dir: artifacts/data_ingestion

# ==============================
# Data Validation Configuration
# ==============================

data_validation:
  # Directory to store data validation outputs
  root_dir: artifacts/data_validation

  # Path to the raw CSV data after unzipping
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv

  # Path to a status file that tracks validation result
  STATUS_FILE: artifacts/data_validation/status.txt

# ==============================
# Data Transformation Configuration
# ==============================

data_transformation:
  # Directory to store transformed data
  root_dir: artifacts/data_transformation

  # Path to the raw input data
  data_path: artifacts/data_ingestion/winequality-red.csv

  # Path to status file (shared with validation status)
  STATUS_FILE: artifacts/data_validation/status.txt

# ==============================
# Model Training Configuration
# ==============================

model_trainer:
  # Directory to save trained model and training logs
  root_dir: artifacts/model_trainer

  # Path to training dataset
  train_data_path: artifacts/data_transformation/train.csv

  # Path to testing dataset
  test_data_path: artifacts/data_transformation/test.csv

  # Filename for the trained model
  model_name: model.joblib

# ==============================
# Model Evaluation Configuration
# ==============================

model_evaluation:
  # Directory for model evaluation outputs
  root_dir: artifacts/model_evaluation

  # Path to testing data used for evaluation
  test_data_path: artifacts/data_transformation/test.csv

  # Path to the trained model file
  model_path: artifacts/model_trainer/model.joblib

  # File to save evaluation metrics like accuracy, F1, etc.
  test_metric_file_path: artifacts/model_evaluation/metrics.json

# ==============================
# Model Prediction Configuration
# ==============================

model_prediction:
  # Directory to store prediction outputs
  root_dir: artifacts/model_prediction

  # Path to the trained model for inference
  model_path: artifacts/model_trainer/model.joblib

  # Output file path for storing predictions
  predictions_file_path: artifacts/model_prediction/predictions.csv
